- name: catalogue configuration
  hosts: catalogue
  become: yes
  tasks:
  - name: disabling nodejs
    ansible.builtin.command: dnf module disable nodejs -y
  - name: enabling nodejs
    ansible.builtin.command: dnf module enable nodejs:20 -y
  - name: install nodejs
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: add app user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
  - name: create app directory
    ansible.builtin.file:
      path: /app  
      state: directory
  - name: download catalogue code
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip 
      dest: /tmp/catalogue.zip
  - name: unzip catalogue code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app 
      remote_src: yes
  - name: install dependencies
    community.general.npm:
      name: npm
      path: /app
  - name: copy catalogue service var_files
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  - name: demon reload
    ansible.builtin.systemd_service:
      name: catalogue
      daemon_reload: true
  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes
  - name: adding repo
    ansible.builtin.copy:
      src: mongo.repo
      dest: /etc/yum.repos.d/mongo.repo
  - name: install mongodb
    ansible.builtin.package:
      name: mongodb
      state: present
  - name: load data
    ansible.builtin.shell: mongosh --host mongodb.sreeja.site </app/db/master-data.js
    




